### PR TITLE
Install Roon 2.0

### LINKED ISSUE #26: Can't install Roon 2.0
Says "this device is not compatible with Roon 2.0"
I don't know how to get details

### PR DESCRIPTION
**Pull request by ThatDonna**
Updated installer to support installing Roon 2.0

Closes #26

### CODE REVIEW

**Comment by trisweb** [comment]
+1 for this, it matches what I changed in the base script to install Roon 2.0.

Could use the new icon as well, will submit a separate PR for that.

**Comment by ThatDonna** [comment]
Cleaned up the installer to not hard-code paths in the start_my_roon_instance.sh script, updated icons from @trisweb, and some README improvements.

Should also close #15

**Comment by JohnFlowerful** [comment]
This will break when VERBOSE=0.

**Comment by spockfish** [comment]
That's been fixed now.

**Pull request merged**
