### PR TITLE
Fix "Resolution too small" error

### PR DESCRIPTION
**Pull request by halfcyan**

### CODE REVIEW

**Comment by marcinulan** [comment]
This fix works for me.

**Comment by spockfish** [comment]
Hi @halfcyan,

Can you provide some description on this PR?
To me it's not entirely sure why this change is needed. If you're not setting this flag you're running Roon without the 'scalefactor' option, which is equal to running it with 'scalefactor=1' .... Or am I missing something?

Thanks

**Comment by vmartell22** [comment]
I think the PR author is misinterpreting the flag - authors think it means "this is the scale factor" as opposed to what it is, "please set the scale factor"

**Comment by spockfish** [comment]
I've reimplemented it: it now actually *is* the scale factor instead of just an enable flag.

**Comment by halfcyan** [comment]
> I think the PR author is misinterpreting the flag - authors think it means "this is the scale factor" as opposed to what it is, "please set the scale factor"

Yeah, I was misinterpreting it. I didn't really know how to read shell scripts when I wrote this so I thought it was setting the scale factor to 1x instead of telling it to set a scale factor.

> I've reimplemented it: it now actually _is_ the scale factor instead of just an enable flag.

This is a much more elegant solution, thanks.

**Pull request closed without merging**
